"""
Test script for the /render endpoint.
"""

import requests
import json
import os
from pathlib import Path

BASE_URL = "http://localhost:8000"

# Render request payloads live in this JSON file so variations can be changed
# without editing the script. Keys: "plan_mode", "with_title", "prompt_mode".
RENDER_INPUT_PATH = Path(__file__).parent / "render_test_input.json"

# Optional: the render-ready plan produced by test_plan_endpoint.py. When present,
# the plan-mode render uses this exact plan instead of the static "plan_mode"
# fallback in render_test_input.json.
GENERATED_PLAN_PATH = Path(__file__).parent / "generated_comp_plan.json"


def load_render_inputs() -> dict:
    """Load the render request payloads from the JSON file."""
    with open(RENDER_INPUT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def load_plan_payload() -> dict:
    """Return the plan-mode payload, preferring the plan endpoint's output.

    If generated_comp_plan.json exists (written by test_plan_endpoint.py), that
    exact plan is rendered; otherwise the static "plan_mode" entry from
    render_test_input.json is used.
    """
    if GENERATED_PLAN_PATH.exists():
        print(f"Using generated plan from: {GENERATED_PLAN_PATH.name}")
        with open(GENERATED_PLAN_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    print(f"No {GENERATED_PLAN_PATH.name} found — using 'plan_mode' from {RENDER_INPUT_PATH.name}")
    return load_render_inputs()["plan_mode"]


def test_render_endpoint():
    """Test the /render endpoint with a composition plan (plan-mode)."""

    url = f"{BASE_URL}/render"

    # Prefer the plan generated by test_plan_endpoint.py, else the static payload
    payload = load_plan_payload()

    print(f"Testing POST {url}")
    print(f"Composition plan chunks: {len(payload.get('chunks', []))}")
    print("-" * 50)

    try:
        response = requests.post(url, json=payload, timeout=300)
        response.raise_for_status()
        
        result = response.json()
        print(f"Status: {response.status_code}")
        print("\n" + "=" * 60)
        print("FULL RESPONSE DETAILS")
        print("=" * 60)
        
        # Print each top-level key and its value
        for key, value in result.items():
            print(f"\n--- {key} ---")
            if isinstance(value, dict):
                print(json.dumps(value, indent=2))
            elif isinstance(value, list):
                print(json.dumps(value, indent=2))
            else:
                print(value)
        
        print("\n" + "=" * 60)
        print("RAW JSON RESPONSE")
        print("=" * 60)
        print(json.dumps(result, indent=2))
        
        # Validate response structure
        assert "filename" in result, "Response missing 'filename'"
        assert "file_path" in result, "Response missing 'file_path'"
        assert "download_url" in result, "Response missing 'download_url'"
        assert "file_size_bytes" in result, "Response missing 'file_size_bytes'"
        assert "request_id" in result, "Response missing 'request_id'"
        
        print("\n✅ Render test passed!")
        return result
        
    except requests.exceptions.ConnectionError:
        print("❌ Error: Could not connect to server. Is it running?")
        return None
    except requests.exceptions.Timeout:
        print("❌ Error: Request timed out. Rendering may take a while.")
        return None
    except requests.exceptions.HTTPError as e:
        print(f"❌ HTTP Error: {e}")
        print(f"Response: {response.text}")
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None


def test_download_endpoint(filename: str):
    """Test the /render/download/{filename} endpoint."""
    
    url = f"{BASE_URL}/render/download/{filename}"
    
    print(f"\nTesting GET {url}")
    print("-" * 50)
    
    try:
        response = requests.get(url, stream=True, timeout=60)
        response.raise_for_status()
        
        # Check content type
        content_type = response.headers.get("Content-Type", "")
        print(f"Content-Type: {content_type}")
        
        # Save to local file for verification
        output_dir = os.path.join(os.path.dirname(__file__), "music")
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"downloaded_{filename}")
        
        with open(output_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
        
        file_size = os.path.getsize(output_path)
        print(f"Downloaded file size: {file_size} bytes")
        print(f"Saved to: {output_path}")
        
        assert file_size > 0, "Downloaded file is empty"
        assert "audio" in content_type or "mpeg" in content_type, f"Unexpected content type: {content_type}"
        
        print("\n✅ Download test passed!")
        return output_path
        
    except requests.exceptions.HTTPError as e:
        print(f"❌ HTTP Error: {e}")
        print(f"Response: {response.text}")
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None


def test_stream_endpoint(filename: str):
    """Test the /render/stream/{filename} endpoint."""
    
    url = f"{BASE_URL}/render/stream/{filename}"
    
    print(f"\nTesting GET {url}")
    print("-" * 50)
    
    try:
        response = requests.get(url, stream=True, timeout=60)
        response.raise_for_status()
        
        # Check headers
        content_type = response.headers.get("Content-Type", "")
        content_length = response.headers.get("Content-Length", "unknown")
        
        print(f"Content-Type: {content_type}")
        print(f"Content-Length: {content_length}")
        
        # Read first chunk to verify streaming works
        first_chunk = next(response.iter_content(chunk_size=8192))
        print(f"First chunk size: {len(first_chunk)} bytes")
        
        assert len(first_chunk) > 0, "Stream returned empty data"
        assert "audio" in content_type or "mpeg" in content_type, f"Unexpected content type: {content_type}"
        
        print("\n✅ Stream test passed!")
        return True
        
    except requests.exceptions.HTTPError as e:
        print(f"❌ HTTP Error: {e}")
        print(f"Response: {response.text}")
        return False
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def test_download_not_found():
    """Test the /render/download endpoint with a non-existent file."""
    
    url = f"{BASE_URL}/render/download/nonexistent_file.mp3"
    
    print(f"\nTesting 404 handling - GET {url}")
    print("-" * 50)
    
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 404:
            print(f"✅ Correctly returned 404 for non-existent file")
            return True
        else:
            print(f"❌ Expected 404, got {response.status_code}")
            return False
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def test_render_endpoint_with_title():
    """Test the /render endpoint with a title for custom filename."""

    url = f"{BASE_URL}/render"

    # Payload loaded from render_test_input.json -> "with_title"
    payload = load_render_inputs()["with_title"]

    print(f"\nTesting POST {url} with title")
    print(f"Payload: {json.dumps(payload, indent=2)}")
    print("-" * 50)

    try:
        response = requests.post(url, json=payload, timeout=120)
        response.raise_for_status()

        result = response.json()
        print(f"Status: {response.status_code}")
        print(f"Response:\n{json.dumps(result, indent=2)}")

        # Verify filename contains the title
        assert "epic_battle_theme" in result["filename"].lower(), \
            f"Filename should contain title: {result['filename']}"

        print("\nTest with title passed!")
        return result

    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to server.")
        return None
    except Exception as e:
        print(f"Error: {e}")
        return None


def test_render_prompt_mode():
    """Test the /render endpoint in prompt-mode with extra pass-through params.

    Exercises the text-prompt path plus music_length_ms and the additional
    compose_detailed parameters (model_id, force_instrumental, output_format).
    """

    url = f"{BASE_URL}/render"

    # Payload loaded from render_test_input.json -> "prompt_mode"
    payload = load_render_inputs()["prompt_mode"]

    print(f"\nTesting POST {url} in prompt-mode (with extra params)")
    print(f"Payload: {json.dumps(payload, indent=2)}")
    print("-" * 50)

    try:
        response = requests.post(url, json=payload, timeout=300)
        response.raise_for_status()

        result = response.json()
        print(f"Status: {response.status_code}")
        print(f"Response:\n{json.dumps(result, indent=2)}")

        # Validate response structure
        assert "filename" in result, "Response missing 'filename'"
        assert "download_url" in result, "Response missing 'download_url'"
        assert "file_size_bytes" in result, "Response missing 'file_size_bytes'"
        # Title should drive the filename
        assert "prompt_mode_track" in result["filename"].lower(), \
            f"Filename should contain title: {result['filename']}"

        print("\n✅ Prompt-mode test passed!")
        return result

    except requests.exceptions.ConnectionError:
        print("❌ Error: Could not connect to server. Is it running?")
        return None
    except requests.exceptions.Timeout:
        print("❌ Error: Request timed out. Rendering may take a while.")
        return None
    except requests.exceptions.HTTPError as e:
        print(f"❌ HTTP Error: {e}")
        print(f"Response: {response.text}")
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None


def test_render_validation():
    """Test the /render endpoint with invalid input.

    Covers the mutual-exclusivity contract between 'prompt' and 'chunks':
    - empty chunks + no prompt  -> 422
    - both prompt and chunks    -> 422
    - music_length_ms w/o prompt -> 422
    """

    url = f"{BASE_URL}/render"

    cases = [
        {
            "name": "empty chunks + no prompt",
            "payload": {"chunks": []},
        },
        {
            "name": "both prompt and chunks (mutually exclusive)",
            "payload": {
                "prompt": "an upbeat track",
                "chunks": [
                    {
                        "text": "[Intro]",
                        "positive_styles": ["120 bpm"],
                        "negative_styles": [],
                        "duration_ms": 4000,
                        "context_adherence": "high",
                    }
                ],
            },
        },
        {
            "name": "music_length_ms without prompt",
            "payload": {
                "music_length_ms": 30000,
                "chunks": [
                    {
                        "text": "[Intro]",
                        "positive_styles": ["120 bpm"],
                        "negative_styles": [],
                        "duration_ms": 4000,
                        "context_adherence": "high",
                    }
                ],
            },
        },
    ]

    all_passed = True
    for case in cases:
        print(f"\nTesting validation - {case['name']} (should return 422)")
        print("-" * 50)
        try:
            response = requests.post(url, json=case["payload"], timeout=60)
            print(f"Status: {response.status_code}")
            if response.status_code == 422:
                print(f"✅ Correctly returned 422 for: {case['name']}")
            else:
                print(f"❌ Expected 422, got {response.status_code}")
                print(f"Response: {response.text[:500]}")
                all_passed = False
        except Exception as e:
            print(f"❌ Error: {e}")
            all_passed = False

    return all_passed


def run_all_tests():
    """Run all render endpoint tests."""

    print("=" * 60)
    print("RENDER ENDPOINT TESTS")
    print("=" * 60)

    # Test 404 handling first (quick test)
    test_download_not_found()

    # Test render with title (custom filename)
    test_render_endpoint_with_title()

    # Test prompt-mode render with extra pass-through params
    test_render_prompt_mode()

    # Test the main render endpoint (composition-plan mode)
    result = test_render_endpoint()

    if result:
        filename = result.get("filename")

        if filename:
            # Test download endpoint
            test_download_endpoint(filename)

            # Test stream endpoint
            test_stream_endpoint(filename)

    # Test validation (mutual-exclusivity rules)
    test_render_validation()
    
    print("\n" + "=" * 60)
    print("TESTS COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    run_all_tests()
