"""
Test script for the `finetune_id` parameter on the ElevenLabs v2 music API.

Calls `music.compose_detailed` directly (bypassing the FastAPI app) with a
prompt plus the "Indie Dance" finetune pulled from `finetunes.json`, then saves
the rendered audio to `testing/music/`.

Docs: https://elevenlabs.io/docs/api-reference/music/compose-detailed

Usage:
    uv run python testing/test_finetune_compose.py
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv
from elevenlabs.client import ElevenLabs

# Load ELEVENLABS_API_KEY from the project .env
load_dotenv(Path(__file__).parent.parent / ".env")

MODEL_ID = "music_v2"
FINETUNE_NAME = "Indie Dance"
MUSIC_LENGTH_MS = 20000  # 20s (min 3000, max 600000)
PROMPT = (
    "An upbeat indie dance track with a driving four-on-the-floor beat, "
    "shimmering synth arpeggios, a groovy bassline, and bright plucked guitars. "
    "Energetic and danceable, made for a late-night rooftop party."
)

FINETUNES_PATH = Path(__file__).parent / "finetunes.json"
OUTPUT_DIR = Path(__file__).parent / "music"


def get_finetune_id(name: str) -> str:
    """Return the finetune id whose name matches `name` from finetunes.json."""
    with open(FINETUNES_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    for ft in data.get("finetunes", []):
        if ft.get("name") == name:
            return ft["id"]

    raise ValueError(f"No finetune named '{name}' found in {FINETUNES_PATH.name}")


def test_compose_with_finetune():
    """Render a track using the Indie Dance finetune via `finetune_id`."""
    api_key = os.getenv("ELEVENLABS_API_KEY")
    if not api_key:
        print("❌ ELEVENLABS_API_KEY is not set (check your .env).")
        return None

    finetune_id = get_finetune_id(FINETUNE_NAME)

    print("=" * 60)
    print("COMPOSE_DETAILED WITH finetune_id")
    print("=" * 60)
    print(f"Finetune:    {FINETUNE_NAME} ({finetune_id})")
    print(f"Model:       {MODEL_ID}")
    print(f"Length (ms): {MUSIC_LENGTH_MS}")
    print(f"Prompt:      {PROMPT}")
    print("-" * 60)

    client = ElevenLabs(api_key=api_key)

    # NOTE: the SDK's custom MusicClient.compose_detailed wrapper silently DROPS
    # finetune_id (it lands in **kwargs and is never sent). We must call the raw
    # autogenerated client and reuse the wrapper's multipart parser — this is the
    # same path RenderService._compose uses in the backend.
    music = client.music
    try:
        with music._raw_client.compose_detailed(
            prompt=PROMPT,
            music_length_ms=MUSIC_LENGTH_MS,
            model_id=MODEL_ID,
            finetune_id=finetune_id,
        ) as r:
            track_details = music._parse_multipart(r.data)
            track_details.song_id = r.headers.get("song-id")
    except Exception as e:
        print(f"❌ compose_detailed failed: {e}")
        return None

    audio_bytes = track_details.audio
    print(f"Returned filename: {track_details.filename}")
    print(f"Audio size:        {len(audio_bytes)} bytes")

    # Save the audio locally for verification
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = OUTPUT_DIR / f"indie_dance_finetune_{finetune_id}.mp3"
    with open(output_path, "wb") as f:
        f.write(audio_bytes)
    print(f"Saved to:          {output_path}")

    # Surface any returned metadata/composition plan for inspection
    json_data = track_details.json if hasattr(track_details, "json") else None
    if json_data:
        print("\n--- song_metadata ---")
        print(json.dumps(json_data.get("song_metadata"), indent=2))

    assert len(audio_bytes) > 0, "Rendered audio is empty"
    print("\n✅ Finetune compose test passed!")
    return output_path


if __name__ == "__main__":
    test_compose_with_finetune()
