"""create renders table

Revision ID: 68a008a079ed
Revises: 
Create Date: 2026-07-19 10:52:13.518100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a008a079ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blob_key', sa.String(length=512), nullable=False),
    sa.Column('blob_url', sa.String(length=1024), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('output_format', sa.String(length=32), nullable=True),
    sa.Column('composition_plan', sa.JSON(), nullable=True),
    sa.Column('song_metadata', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_blob_key'), 'renders', ['blob_key'], unique=True)
    op.create_index(op.f('ix_renders_filename'), 'renders', ['filename'], unique=False)
    op.create_index(op.f('ix_renders_request_id'), 'renders', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renders_request_id'), table_name='renders')
    op.drop_index(op.f('ix_renders_filename'), table_name='renders')
    op.drop_index(op.f('ix_renders_blob_key'), table_name='renders')
    op.drop_table('renders')
    # ### end Alembic commands ###
